-- Write SQL queries to perform the following tasks using the Sakila database:
-- 1. List the number of films per category.
SELECT category_id, COUNT(film_id) FROM sakila.film_category
GROUP BY category_id;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT s.store_id, ci.city, co.country FROM sakila.store AS s
JOIN sakila.address AS a
ON s.address_id = a.address_id
JOIN sakila.city AS ci
ON a.city_id = ci.city_id
JOIN sakila.country AS co
ON ci.country_id = co.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.
SELECT c.store_id AS Store_ID, SUM(p.amount) AS Revenue FROM sakila.customer AS c
JOIN sakila.payment AS p
ON c.customer_id = p.customer_id
GROUP BY c.store_id;

-- 4. Determine the average running time of films for each category.
SELECT fc.category_id AS Category, AVG(f.length) AS Average_Length FROM sakila.film_category as fc
JOIN sakila.film AS f
ON fc.film_id = f.film_id
GROUP BY fc.category_id;

-- Bonus:

-- 5. Identify the film categories with the longest average running time.
SELECT fc.category_id AS Category, AVG(f.length) AS Average_Length FROM sakila.film_category as fc
JOIN sakila.film AS f
ON fc.film_id = f.film_id
GROUP BY fc.category_id
ORDER BY Average_Length DESC;

-- 6. Display the top 10 most frequently rented movies in descending order.
SELECT f.title AS Title, COUNT(r.rental_date) AS Amount_Rental FROM sakila.film AS f
JOIN sakila.inventory AS i
ON f.film_id = i.film_id
JOIN sakila.rental AS r
ON i.inventory_id = r.inventory_id
GROUP BY Title
ORDER BY Amount_Rental desc
LIMIT 10;

-- 7. Determine if "Academy Dinosaur" can be rented from Store 1.
select s.store_id as Store_ID, f.title as Title, COUNT(f.title) as Stock from sakila.film as f
join sakila.inventory as i
on f.film_id = i.film_id
join sakila.store as s
on i.store_id = s.store_id
where Title = 'Academy Dinosaur'
group by Store_ID;


-- 8. Provide a list of all distinct film titles, along with their availability status in the inventory. Include a column indicating whether each title is 'Available' or 'NOT available.' Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."

